// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bpiuhxirklmxdleaepjm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJwaXVoeGlya2xteGRsZWFlcGptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzMzY0MTUsImV4cCI6MjA3MDkxMjQxNX0.c7LzXvDn741m52pMX6Q4QpY0cIduEHslKiJAtP8M4NE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});